ardusub_manager:
  ros__parameters:
    message_intervals:
      ids: [31, 32]
      rates: [50.0, 50.0]
    set_ekf_origin: true
    ekf_origin:
        latitude: 41.358389  # 41°21'30.2"N
        longitude: 2.185278  # 2°11'7.0"E
        altitude: 0.0
    publish_tf: false
