mavros:
  ros__parameters:
    system_id: 255
    plugin_allowlist:
      - sys_status
      - command
      - imu
      - rc_io
      - param
      - vision*
      - local*
      - global_position
      - mavros_sensor
    mavros_sensor:
      sensor_topic: "/sensors/generalized_sensor_test"
      mavros_topic: "/mavros/custom_vision_speed/speed_twist"
      publish_mavlink: false

mavros_node:
  ros__parameters:
    fcu_url: "udp://:14755@0.0.0.0:14755"
    gcs_url: "udp://@192.168.2.1:14550"

mavros/local_position:
  ros__parameters:
    frame_id: "map"
    tf:
      send: true
