controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100 # Hz

    adaptive_integral_terminal_sliding_mode_controller:
      type: velocity_controllers/AdaptiveIntegralTerminalSlidingModeController

    thruster_allocation_matrix_controller:
      type: thruster_allocation_matrix_controller/ThrusterAllocationMatrixController

    thruster1_controller:
      type: thruster_controllers/PolynomialThrustCurveController

    thruster2_controller:
      type: thruster_controllers/PolynomialThrustCurveController

    thruster3_controller:
      type: thruster_controllers/PolynomialThrustCurveController

    thruster4_controller:
      type: thruster_controllers/PolynomialThrustCurveController

    thruster5_controller:
      type: thruster_controllers/PolynomialThrustCurveController

    thruster6_controller:
      type: thruster_controllers/PolynomialThrustCurveController

adaptive_integral_terminal_sliding_mode_controller:
  ros__parameters:
    use_sim_time: true
    use_external_measured_states: true
    reference_controller: thruster_allocation_matrix_controller
    gains:
      lambda: 0.9
      x:
        alpha: 12.0
        k1_min: 0.1
        k2: 0.4
        k_theta: 2.0
        mu: 0.01
      y:
        alpha: 12.0
        k1_min: 0.1
        k2: 0.4
        k_theta: 2.0
        mu: 0.01
      z:
        alpha: 12.0
        k1_min: 0.4
        k2: 0.8
        k_theta: 2.0
        mu: 0.01
      rx:
        alpha: 0.5
        k1_min: 0.1
        k2: 0.4
        k_theta: 2.0
        mu: 0.01
      ry:
        alpha: 12.0
        k1_min: 0.1
        k2: 1.0
        k_theta: 2.0
        mu: 0.01
      rz:
        alpha: 12.0
        k1_min: 0.1
        k2: 0.4
        k_theta: 2.0
        mu: 0.01
    tf:
      base_frame: "base_link_fsd"
      odom_frame: "map_ned"
    hydrodynamics:
      mass: 16.61
      weight: 98.1
      buoyancy: 159.91
      moments_of_inertia: [0.24, 0.2, 0.4]
      added_mass: [-12.7, -10.5, -14.57, -0.12, -0.12, -0.12]
      center_of_buoyancy: [0.0, 0.0, 0.0]
      center_of_gravity: [0.0, 0.0, 0.0]
      linear_damping: [-28.23, -18.29, -23.51, -0.31, -0.31, -0.31]
      quadratic_damping: [-93.47, -74.28, -168.17, -1.55, -1.55, -1.55]

thruster_allocation_matrix_controller:
  ros__parameters:
    thrusters:
      - thruster1_joint
      - thruster2_joint
      - thruster3_joint
      - thruster4_joint
      - thruster5_joint
      - thruster6_joint
    reference_controllers:
      - thruster1_controller
      - thruster2_controller
      - thruster3_controller
      - thruster4_controller
      - thruster5_controller
      - thruster6_controller
    tam:
      x:  [ -0.707,  -0.707,   0.707,  0.707,      0.0,     0.0]
      y:  [ 0.707,   -0.707,   0.707, -0.707,      0.0,     0.0]
      z:  [    0.0,     0.0,     0.0,    0.0,      1.0,     1.0]
      rx: [    0.0,     0.0,     0.0,    0.0, -0.21805, 0.21805]
      ry: [    0.0,     0.0,     0.0,    0.0,    -0.12,   -0.12]
      rz: [0.1888,  -0.1888, -0.1888, 0.1888,      0.0,     0.0]

thruster1_controller:
  ros__parameters:
    use_sim_time: true
    thruster: thruster1_joint
    min_thrust: -40.0
    max_thrust: 60.0
    min_deadband: 1470
    max_deadband: 1530
    neutral_pwm: 1500
    thrust_curve_coefficients: [1498.0, 12.01, -0.04731, -0.002098, 0.00002251]

thruster2_controller:
  ros__parameters:
    use_sim_time: true
    thruster: thruster2_joint
    min_thrust: -40.0
    max_thrust: 60.0
    min_deadband: 1470
    max_deadband: 1530
    neutral_pwm: 1500
    thrust_curve_coefficients: [1498.0, 12.01, -0.04731, -0.002098, 0.00002251]

thruster3_controller:
  ros__parameters:
    use_sim_time: true
    thruster: thruster3_joint
    min_thrust: -40.0
    max_thrust: 60.0
    min_deadband: 1470
    max_deadband: 1530
    neutral_pwm: 1500
    thrust_curve_coefficients: [1498.0, 12.01, -0.04731, -0.002098, 0.00002251]

thruster4_controller:
  ros__parameters:
    use_sim_time: true
    thruster: thruster4_joint
    min_thrust: -40.0
    max_thrust: 60.0
    min_deadband: 1470
    max_deadband: 1530
    neutral_pwm: 1500
    thrust_curve_coefficients: [1498.0, 12.01, -0.04731, -0.002098, 0.00002251]

thruster5_controller:
  ros__parameters:
    use_sim_time: true
    thruster: thruster5_joint
    min_thrust: -40.0
    max_thrust: 60.0
    min_deadband: 1470
    max_deadband: 1530
    neutral_pwm: 1500
    thrust_curve_coefficients: [1498.0, 12.01, -0.04731, -0.002098, 0.00002251]

thruster6_controller:
  ros__parameters:
    use_sim_time: true
    thruster: thruster6_joint
    min_thrust: -40.0
    max_thrust: 60.0
    min_deadband: 1470
    max_deadband: 1530
    neutral_pwm: 1500
    thrust_curve_coefficients: [1498.0, 12.01, -0.04731, -0.002098, 0.00002251]