/control_integration/message_transforms:
  ros__parameters:

    incoming_topics:
      - /odometry/filtered_enu

    transforms:
      /odometry/filtered_enu:
        outgoing_topic: /adaptive_integral_terminal_sliding_mode_controller/system_state
        message_type: nav_msgs/msg/Odometry
        frame_id: odom
        child_frame_id: base_link
