<?xml version="1.0"?>
<package format="3">
  <name>current_system</name>
  <version>0.0.1</version>
  <description>Minimal constant-current plugin for GZ Sim</description>
  <maintainer email="lublu@hotmail.ch">Luis Blunschi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>gz-sim8</exec_depend>
  <build_depend>gz-sim8</build_depend>
</package>
