ekf_filter_node:
  ros__parameters:
      #Declare the frequency of the EKF update
      frequency: 10.0

      two_d_mode: false

      publish_tf: true

      map_frame: map
      odom_frame: odom
      base_link_frame: base_link
      world_frame: odom

      # When declaring parameters, do it in the following way:
      # Declare the sensor by the type of message you're receiving(odom, imu, twist)
      # odomi: /name/of/topic
      # next define which data you'll be reading from it:
      # odomi_config = [x_pos, y_pos, z_pos,
      #                 roll, pitch, yaw,
      #                 x_vel, y_vel, z_vel,
      #                 roll_vel, pitch_vel, yaw_vel
      #                 x_accel, y_accel, z_accel]
      # Each of which gets a boolean value

      # first configure the data coming from the pixhawk IMU
      odom0: /mavros/local_position/odom
      odom0_config: [true, true, true,
                       true, true, true,
                       false, false, false,
                       false, false, false,
                       false, false, false]

      # now configure the data coming from the DVL
      twist0: /dvl/velocity
      twist0_config: [false, false, false,
                      false, false, false,
                      true, true, true,
                      false, false, false,
                      false, false, false]

      # Now configure the data coming from the vectornav IMU
      imu0_remove_gravitational_acceleration: true #remove the constant gravity 
      imu0: /vn100/gz_data
      imu0_config: [false, false, false,
                      true, true, true,
                      false, false, false,
                      true, true, true,
                      true, true, true]
